{% set version = "1.16" %}

package:
  name: fuse-overlayfs
  version: {{ version }}

source:
  - url: https://github.com/containers/fuse-overlayfs/archive/v{{ version }}.tar.gz
    sha256: 45968517603389ead067222d234bc8d8ed33e4b4f8ba16216bdd3e6aedcccea9

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autoconf >=2.69
    - automake >=1.9
    - make
    - pkg-config >=0.9.0
  host:
    - libfuse3

test:
  commands:
    - fuse-overlayfs --help
    - fuse-overlayfs --version

about:
  home: https://github.com/containers/fuse-overlayfs
  dev_url: https://github.com/containers/fuse-overlayfs
  doc_url: https://github.com/containers/fuse-overlayfs
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: fuse-overlayfs - overlayfs FUSE implementation
  description: >
    fuse-overlayfs provides an overlayfs FUSE implementation so that it can be used since Linux 4.18 by unprivileged users in an user namespace.

extra:
  recipe-maintainers:
    - xhochy
    - mbargull
