{% set version = "1.3.0" %}

package:
  name: fuse-overlayfs
  version: {{ version }}

source:
  - url: https://github.com/containers/fuse-overlayfs/archive/v{{ version }}.tar.gz
    sha256: 91e78a93aac7698c65083deea04952bc86af6abbb0830785ef1dd4a8707ad8bf
    patches:
      - 0001-Add-missing-defines-for-CentOS-6.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf >=2.69
    - automake >=1.9
    - make
    - pkg-config >=0.9.0
  host:
    - libfuse >=3.2.1
    - libfuse
  run:
    # We can remove this here once we depend on a libfuse version for which we
    # know all builds carry a run_exports.
    - {{ pin_compatible('libfuse', max_pin='x') }}

test:
  commands:
    - fuse-overlayfs --help
    - fuse-overlayfs --version

about:
  home: https://github.com/containers/fuse-overlayfs
  dev_url: https://github.com/containers/fuse-overlayfs
  doc_url: https://github.com/containers/fuse-overlayfs
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: fuse-overlayfs - overlayfs FUSE implementation
  description: >
    fuse-overlayfs provides an overlayfs FUSE implementation so that it can be used since Linux 4.18 by unprivileged users in an user namespace.

extra:
  recipe-maintainers:
    - xhochy
    - mbargull
